"""Binary parity arbitrage from §4A.

A = ask_YES + ask_NO + costs
If A < 1 - ε → buy both sides

B = bid_YES + bid_NO - costs
If B > 1 + ε → split collateral into YES/NO, sell both

Pure structure. No prediction needed.
"""

from __future__ import annotations

import structlog
from pydantic import BaseModel

from pmm1.state.books import OrderBook

logger = structlog.get_logger(__name__)


class ParitySignal(BaseModel):
    """Result of a parity check — describes the arb opportunity if any."""

    condition_id: str
    signal_type: str  # "buy_both" or "sell_both"
    ask_yes: float = 0.0
    ask_no: float = 0.0
    bid_yes: float = 0.0
    bid_no: float = 0.0
    total_cost: float = 0.0
    edge: float = 0.0  # How much below 1 (buy) or above 1 (sell)
    max_size: float = 0.0
    fee_estimate: float = 0.0
    is_actionable: bool = False


class ArbOrderIntent(BaseModel):
    """An order intent generated by the parity detector."""

    token_id: str
    side: str  # BUY or SELL
    price: str
    size: str
    strategy: str = "parity_arb"
    order_type: str = "FOK"  # Arb should be all-or-nothing
    neg_risk: bool = False
    condition_id: str = ""
    intent_tag: str = ""


class BinaryParityDetector:
    """Detects and generates arb orders for binary parity violations.

    Binary market: YES + NO should sum to $1.00.
    When they don't (after fees), there's an arb.
    """

    def __init__(
        self,
        epsilon: float = 0.005,  # 0.5¢ minimum edge
        fee_rate: float = 0.002,  # 20bps per side
        min_size: float = 10.0,
        max_size: float = 500.0,
    ) -> None:
        self.epsilon = epsilon
        self.fee_rate = fee_rate
        self.min_size = min_size
        self.max_size = max_size

    def _estimate_fees(self, price: float, size: float) -> float:
        """Estimate fee for a single leg.

        fee = C × p × feeRate × (p(1−p))^exponent
        Simplified for v1: fee ≈ price × size × fee_rate
        """
        return price * size * self.fee_rate

    def check_buy_both(
        self,
        book_yes: OrderBook,
        book_no: OrderBook,
        condition_id: str = "",
    ) -> ParitySignal | None:
        """Check if buying both YES and NO is profitable.

        A = ask_YES + ask_NO + costs
        If A < 1 - ε → buy both sides

        We buy at the ask prices. Total cost should be < $1 per pair.
        """
        ask_yes = book_yes.get_best_ask()
        ask_no = book_no.get_best_ask()

        if ask_yes is None or ask_no is None:
            return None

        ask_y = ask_yes.price_float
        ask_n = ask_no.price_float

        # Max size is limited by available depth on both sides
        max_size = min(
            ask_yes.size_float,
            ask_no.size_float,
            self.max_size,
        )

        if max_size < self.min_size:
            return None

        # Total cost to buy one pair
        fee_yes = self._estimate_fees(ask_y, 1.0)
        fee_no = self._estimate_fees(ask_n, 1.0)
        total_cost = ask_y + ask_n + fee_yes + fee_no

        edge = 1.0 - total_cost  # Positive = profitable

        signal = ParitySignal(
            condition_id=condition_id,
            signal_type="buy_both",
            ask_yes=ask_y,
            ask_no=ask_n,
            total_cost=total_cost,
            edge=edge,
            max_size=max_size,
            fee_estimate=fee_yes + fee_no,
            is_actionable=edge > self.epsilon,
        )

        if signal.is_actionable:
            logger.info(
                "parity_buy_both_detected",
                condition_id=condition_id[:16],
                ask_yes=ask_y,
                ask_no=ask_n,
                edge=f"{edge:.4f}",
                max_size=max_size,
            )

        return signal

    def check_sell_both(
        self,
        book_yes: OrderBook,
        book_no: OrderBook,
        condition_id: str = "",
    ) -> ParitySignal | None:
        """Check if selling both YES and NO is profitable.

        B = bid_YES + bid_NO - costs
        If B > 1 + ε → sell both sides (need to split collateral first)

        We sell at the bid prices. Total proceeds should be > $1 per pair.
        """
        bid_yes = book_yes.get_best_bid()
        bid_no = book_no.get_best_bid()

        if bid_yes is None or bid_no is None:
            return None

        bid_y = bid_yes.price_float
        bid_n = bid_no.price_float

        max_size = min(
            bid_yes.size_float,
            bid_no.size_float,
            self.max_size,
        )

        if max_size < self.min_size:
            return None

        fee_yes = self._estimate_fees(bid_y, 1.0)
        fee_no = self._estimate_fees(bid_n, 1.0)
        total_proceeds = bid_y + bid_n - fee_yes - fee_no

        edge = total_proceeds - 1.0  # Positive = profitable

        signal = ParitySignal(
            condition_id=condition_id,
            signal_type="sell_both",
            bid_yes=bid_y,
            bid_no=bid_n,
            total_cost=1.0,  # Cost to split $1 into YES+NO
            edge=edge,
            max_size=max_size,
            fee_estimate=fee_yes + fee_no,
            is_actionable=edge > self.epsilon,
        )

        if signal.is_actionable:
            logger.info(
                "parity_sell_both_detected",
                condition_id=condition_id[:16],
                bid_yes=bid_y,
                bid_no=bid_n,
                edge=f"{edge:.4f}",
                max_size=max_size,
            )

        return signal

    def generate_orders(
        self,
        signal: ParitySignal,
        token_id_yes: str,
        token_id_no: str,
        size_fraction: float = 0.5,
    ) -> list[ArbOrderIntent]:
        """Generate order intents from a parity signal.

        Args:
            signal: The detected parity signal.
            token_id_yes: YES token ID.
            token_id_no: NO token ID.
            size_fraction: Fraction of max_size to use (conservative).
        """
        if not signal.is_actionable:
            return []

        size = min(signal.max_size * size_fraction, self.max_size)
        if size < self.min_size:
            return []

        size_str = f"{size:.2f}"
        orders: list[ArbOrderIntent] = []

        if signal.signal_type == "buy_both":
            orders.append(ArbOrderIntent(
                token_id=token_id_yes,
                side="BUY",
                price=f"{signal.ask_yes:.4f}",
                size=size_str,
                strategy="parity_arb",
                order_type="FOK",
                condition_id=signal.condition_id,
                intent_tag=f"parity_buy_yes_{signal.condition_id[:8]}",
            ))
            orders.append(ArbOrderIntent(
                token_id=token_id_no,
                side="BUY",
                price=f"{signal.ask_no:.4f}",
                size=size_str,
                strategy="parity_arb",
                order_type="FOK",
                condition_id=signal.condition_id,
                intent_tag=f"parity_buy_no_{signal.condition_id[:8]}",
            ))
        elif signal.signal_type == "sell_both":
            orders.append(ArbOrderIntent(
                token_id=token_id_yes,
                side="SELL",
                price=f"{signal.bid_yes:.4f}",
                size=size_str,
                strategy="parity_arb",
                order_type="FOK",
                condition_id=signal.condition_id,
                intent_tag=f"parity_sell_yes_{signal.condition_id[:8]}",
            ))
            orders.append(ArbOrderIntent(
                token_id=token_id_no,
                side="SELL",
                price=f"{signal.bid_no:.4f}",
                size=size_str,
                strategy="parity_arb",
                order_type="FOK",
                condition_id=signal.condition_id,
                intent_tag=f"parity_sell_no_{signal.condition_id[:8]}",
            ))

        return orders

    def scan(
        self,
        book_yes: OrderBook,
        book_no: OrderBook,
        condition_id: str,
        token_id_yes: str,
        token_id_no: str,
    ) -> list[ArbOrderIntent]:
        """Full scan: check both directions and generate orders if actionable."""
        all_orders: list[ArbOrderIntent] = []

        # Check buy-both
        buy_signal = self.check_buy_both(book_yes, book_no, condition_id)
        if buy_signal and buy_signal.is_actionable:
            all_orders.extend(self.generate_orders(
                buy_signal, token_id_yes, token_id_no
            ))

        # Check sell-both
        sell_signal = self.check_sell_both(book_yes, book_no, condition_id)
        if sell_signal and sell_signal.is_actionable:
            all_orders.extend(self.generate_orders(
                sell_signal, token_id_yes, token_id_no
            ))

        return all_orders
